# Generated by Django 5.2.7 on 2025-10-16 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='drfpost',
            options={'ordering': ['uploaded_date']},
        ),
        migrations.AddField(
            model_name='drfpost',
            name='jenis',
            field=models.CharField(choices=[('mhs', 'Mahasiswa'), ('dsn', 'Dosen')], default='mhs', max_length=3),
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=100)),
                ('dosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswas', to='basic_api.dosen')),
            ],
        ),
    ]
